# Generated by Django 5.1.1 on 2024-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('unitario', 'Precio Unitario'), ('media-doc', 'Media Docena'), ('docena', 'Docena'), ('por-kilo', 'Por Kilo')], default='unitario', max_length=20, verbose_name='Tipo de Precio'),
        ),
    ]
